behaviors:
  TerrainGenerator:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 1024
      learning_rate: 0.0006
      beta: 0.006
      epsilon: 0.15
      lambd: 0.92
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.2
        gamma: 0.9
        encoding_size: 128
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 750000
    time_horizon: 64
    summary_freq: 100
    threaded: true
environment_parameters:
  lessonID:
    curriculum:
    #  - name: ValidValues
    #    completion_criteria:
    #      measure: reward
    #      behavior: TerrainGenerator
    #      signal_smoothing: true
    #      min_lesson_length: 100
    #      threshold: 85
    #    value: -1
      - name: GoodNormals
        completion_criteria:
          measure: reward
          behavior: TerrainGenerator
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 50
        value: 1
      - name: GoodWater
        completion_criteria:
          measure: reward
          behavior: TerrainGenerator
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 50
        value: 2
      - name: Goodslope
        completion_criteria:
          measure: reward
          behavior: TerrainGenerator
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 50
        value: 3
      - name: RegularTraining
        value: 4