behaviors:
  TerrainGenerator:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0006
      learning_rate_schedule: constant
      batch_size: 128
      buffer_size: 100000
      buffer_init_steps: 200
      tau: 0.005
      save_replay_buffer: false
      init_entcoef: 1.0
      steps_per_update: 5.0
      reward_signal_steps_per_update: 5.0
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.9
        gamma: 0.99
        encoding_size: 128
    keep_checkpoints: 5
    max_steps: 750000
    time_horizon: 64
    summary_freq: 100
    threaded: true
environment_parameters:
  lessonID:
    curriculum:
      - name: ValidValues
        completion_criteria:
          measure: reward
          behavior: TerrainGenerator
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4000
        value: -1
      - name: GoodNormals
        completion_criteria:
          measure: reward
          behavior: TerrainGenerator
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4000
        value: 1
      - name: GoodWater
        completion_criteria:
          measure: reward
          behavior: TerrainGenerator
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4000
        value: 2
      - name: Goodslope
        completion_criteria:
          measure: reward
          behavior: TerrainGenerator
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4000
        value: 3
      - name: RegularTraining
        value: 4