behaviors:
  TerrainGenerator:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 1024
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.9
        gamma: 0.99
        encoding_size: 128
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 100000
    time_horizon: 64
    summary_freq: 500
    threaded: true
environment_parameters:
  lessonID:
    curriculum:
      - name: ValidValues
        completion_criteria:
          measure: reward
          behavior: TerrainGenerator
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 3000
        value: -1
      - name: GoodNormals
        completion_criteria:
          measure: reward
          behavior: TerrainGenerator
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4000
        value: 1
      - name: GoodWater
        completion_criteria:
          measure: reward
          behavior: TerrainGenerator
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4000
        value: 2
      - name: Goodslope
        completion_criteria:
          measure: reward
          behavior: TerrainGenerator
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4000
        value: 3
      - name: RegularTraining
        value: 4