behaviors:
  TerrainGenerator:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 5000
      learning_rate: 3.0e-3
      beta: 5.0e-4
      epsilon: 0.1
      lambd: 0.99997
      num_epoch: 500
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 32
    reward_signals:
      extrinsic:
        gamma: 0.99998
        strength: 0.9
    max_steps: 50000
    time_horizon: 64
    summary_freq: 500