behaviors:
  TerrainGenerator:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0006
      learning_rate_schedule: constant
      batch_size: 128
      buffer_size: 100000
      buffer_init_steps: 200
      tau: 0.005
      steps_per_update: 5.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 5.0
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.9
        encoding_size: 128
        learning_rate: 0.0003
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 750000
    time_horizon: 64
    summary_freq: 100
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters:
  lessonID:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1685
          value: -1
      name: ValidValues
      completion_criteria:
        measure: reward
        behavior: TerrainGenerator
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 3000.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1686
          value: 1
      name: GoodNormals
      completion_criteria:
        measure: reward
        behavior: TerrainGenerator
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 3000.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1687
          value: 2
      name: GoodWater
      completion_criteria:
        measure: reward
        behavior: TerrainGenerator
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 1500.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1688
          value: 3
      name: Goodslope
      completion_criteria:
        measure: reward
        behavior: TerrainGenerator
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 1500.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1689
          value: 4
      name: RegularTraining
      completion_criteria: null
checkpoint_settings:
  run_id: terrainGenControlStepLessonLessDivs
  initialize_from: null
  load_model: false
  resume: true
  force: false
  train_model: false
  inference: false
debug: false
