behaviors:
  TerrainGenerator:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 5
      buffer_size: 50
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 20.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 20.0
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 10
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.9
        encoding_size: 128
        learning_rate: 0.0003
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 10000
    time_horizon: 64
    summary_freq: 100
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters:
  small_wall_height:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 8294
          value: 1.5
      name: Lesson0
      completion_criteria:
        measure: progress
        behavior: SmallWallJump
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.1
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 8295
          value: 2.0
      name: Lesson1
      completion_criteria:
        measure: progress
        behavior: SmallWallJump
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 8296
          value: 2.5
      name: Lesson2
      completion_criteria:
        measure: progress
        behavior: SmallWallJump
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.5
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 8297
          value: 4.0
      name: Lesson3
      completion_criteria: null
  heightMultiplier:
    curriculum:
    - value:
        sampler_type: uniform
        sampler_parameters:
          seed: 8298
          min_value: 30.0
          max_value: 200.0
      name: heightMultiplier
      completion_criteria: null
  noiseEstimatorVariable:
    curriculum:
    - value:
        sampler_type: uniform
        sampler_parameters:
          seed: 8299
          min_value: 1.0
          max_value: 2.5
      name: noiseEstimatorVariable
      completion_criteria: null
  noiseScale:
    curriculum:
    - value:
        sampler_type: uniform
        sampler_parameters:
          seed: 8300
          min_value: 20.0
          max_value: 200.0
      name: noiseScale
      completion_criteria: null
  noiseOctaves:
    curriculum:
    - value:
        sampler_type: uniform
        sampler_parameters:
          seed: 8301
          min_value: 4.0
          max_value: 14.0
      name: noiseOctaves
      completion_criteria: null
  noisePersistence:
    curriculum:
    - value:
        sampler_type: uniform
        sampler_parameters:
          seed: 8302
          min_value: 0.4
          max_value: 0.9
      name: noisePersistence
      completion_criteria: null
  noiseLacunarity:
    curriculum:
    - value:
        sampler_type: uniform
        sampler_parameters:
          seed: 8303
          min_value: 2.0
          max_value: 5.0
      name: noiseLacunarity
      completion_criteria: null
  noiseSeed:
    curriculum:
    - value:
        sampler_type: uniform
        sampler_parameters:
          seed: 8304
          min_value: -500.0
          max_value: 500.0
      name: noiseSeed
      completion_criteria: null
  waterLevel:
    curriculum:
    - value:
        sampler_type: uniform
        sampler_parameters:
          seed: 8305
          min_value: 1.0
          max_value: 5.0
      name: waterLevel
      completion_criteria: null
checkpoint_settings:
  run_id: terrainGenRandomizeControlStep
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
debug: false
